/* Advanced Methods &amp; Algorithms — Quiz Data (Bilingual)
 * 題型 type: "single" 單選 | "multi" 多選 | "tf" 是非
 */
window.QUIZ_DATA = {
  advmethods: {
    label: "進階方法演算法 互動考題",
    label_en: "Advanced Methods Interactive Quiz",
    chapters: [
      { id:"ch01", num:1,  title:"Chatterjee ξ",        title_en:"Chatterjee ξ" },
      { id:"ch02", num:2,  title:"HSIC / dCor",          title_en:"HSIC / dCor" },
      { id:"ch03", num:3,  title:"Mutual Information",   title_en:"Mutual Information" },
      { id:"ch04", num:4,  title:"Optimal Transport",    title_en:"Optimal Transport" },
      { id:"ch05", num:5,  title:"持久同調 (TDA)",        title_en:"Persistent Homology (TDA)" },
      { id:"ch06", num:6,  title:"進階流形學習",          title_en:"Manifold Learning" },
      { id:"ch07", num:7,  title:"RNA Velocity",         title_en:"RNA Velocity" },
      { id:"ch08", num:8,  title:"循環追蹤 (Cycle)",      title_en:"Cycle-following" },
      { id:"ch09", num:9,  title:"圖訊號 & GNN",          title_en:"Graph Signal &amp; GNN" },
      { id:"ch10", num:10, title:"空間統計",              title_en:"Spatial Statistics" },
      { id:"ch11", num:11, title:"變分推論 / VAE",        title_en:"Variational Inference / VAE" },
      { id:"ch12", num:12, title:"擴散模型",              title_en:"Diffusion Models" },
      { id:"ch13", num:13, title:"scLLMs",               title_en:"scLLMs" },
      { id:"ch14", num:14, title:"因果推論",              title_en:"Causal Inference" },
      { id:"ch15", num:15, title:"雙曲嵌入",              title_en:"Hyperbolic Embeddings" },
      { id:"ch16", num:16, title:"Neural ODE",          title_en:"Neural ODE" },
      { id:"ch17", num:17, title:"Flow Matching",       title_en:"Flow Matching" },
      { id:"ch18", num:18, title:"SSM / Mamba",         title_en:"SSM / Mamba" },
      { id:"ch19", num:19, title:"Conformal Prediction",title_en:"Conformal Prediction" },
      { id:"ch20", num:20, title:"主動學習 / BO",         title_en:"Active Learning / BO" },
      { id:"ch21", num:21, title:"Information Bottleneck",title_en:"Information Bottleneck" },
      { id:"ch22", num:22, title:"張量分解",              title_en:"Tensor Decompositions" },
      { id:"ch23", num:23, title:"對比學習",              title_en:"Contrastive Learning" },
      { id:"ch24", num:24, title:"符號回歸",              title_en:"Symbolic Regression" },
      { id:"ch25", num:25, title:"Sheaf",               title_en:"Sheaves" },
      { id:"ch26", num:26, title:"幾何深度學習",          title_en:"Geometric Deep Learning" },
      { id:"ch27", num:27, title:"Modern Hopfield",     title_en:"Modern Hopfield" },
      { id:"ch28", num:28, title:"EBM &amp; DCA",            title_en:"EBM &amp; DCA" },
      { id:"ch29", num:29, title:"Hawkes 點過程",         title_en:"Hawkes &amp; Point Processes" },
      { id:"ch30", num:30, title:"強化學習",              title_en:"Reinforcement Learning" },
      { id:"ch31", num:31, title:"隨機矩陣理論",          title_en:"Random Matrix Theory" },
      { id:"ch32", num:32, title:"Sliced-Wasserstein",  title_en:"Sliced-Wasserstein" },
      { id:"ch33", num:33, title:"壓縮感測",              title_en:"Compressed Sensing" },
      { id:"ch34", num:34, title:"小波",                 title_en:"Wavelets" },
      { id:"ch35", num:35, title:"隱式神經表徵",          title_en:"Implicit Neural Rep." },
      { id:"ch36", num:36, title:"DPP",                 title_en:"DPP" },
      { id:"ch37", num:37, title:"聯邦學習",              title_en:"Federated Learning" },
      { id:"ch38", num:38, title:"超圖學習",              title_en:"Hypergraph Learning" }
    ],
    questions: {
      ch01: [
        { type:"single", stem:"下列關係，Pearson r ≈ 0 但 Chatterjee ξ 仍能偵測到的是？", stem_en:"Which has Pearson r ≈ 0 but ξ still detects?",
          A:"Y = 2X + 3", A_en:"Y = 2X + 3", B:"Y = log(X)", B_en:"Y = log(X)",
          C:"Y = X² 在 X ∈ [−1, 1]", C_en:"Y = X² on X ∈ [−1, 1]",
          D:"Y 與 X 獨立", D_en:"Y independent of X", ans:"C",
          exp:"對稱二次關係 Pearson 抵銷掉，但 ξ 看得到強函數依賴。",
          exp_en:"Symmetric quadratic cancels in Pearson, but ξ sees the strong dependency." },
        { type:"single", stem:"Chatterjee ξ 的時間複雜度為何？", stem_en:"Time complexity of ξ?",
          A:"O(n log n)", A_en:"O(n log n)", B:"O(n²)", B_en:"O(n²)",
          C:"O(n³)", C_en:"O(n³)", D:"O(2ⁿ)", D_en:"O(2ⁿ)", ans:"A",
          exp:"主要成本來自排序，因此 O(n log n)。", exp_en:"Sorting dominates." },
        { type:"single", stem:"ξ 的不對稱性主要用途是？", stem_en:"Main use of ξ asymmetry?",
          A:"加速計算", A_en:"Speed-up", B:"推估調控方向", B_en:"Infer regulatory direction",
          C:"與 R² 等價", C_en:"Equivalent to R²", D:"處理缺失值", D_en:"Handle NA", ans:"B",
          exp:"不對稱性提供方向證據。", exp_en:"Asymmetry provides directional evidence." },
        { type:"tf", stem:"ξ 對純線性高斯資料的統計檢力高於 Pearson r。", stem_en:"ξ has higher power than Pearson for linear Gaussian data.",
          ans:"F", exp:"純線性下 Pearson 最強；ξ 為非單調設計。", exp_en:"For pure linear, Pearson wins; ξ is for non-monotonic." },
        { type:"multi", stem:"以下何者是 Chatterjee ξ 的優勢？(多選)", stem_en:"Which are advantages of ξ? (multi)",
          A:"O(n log n) 計算", A_en:"O(n log n)", B:"偵測非單調依賴", B_en:"Non-monotonic detection",
          C:"輸出方向", C_en:"Directional output", D:"自動處理缺失值", D_en:"Auto-handles NA",
          ans:["A","B","C"], exp:"A、B、C 都是 ξ 真實優勢；缺失值需另外處理。", exp_en:"A, B, C are real; NA still needs handling." }
      ],
      ch02: [
        { type:"single", stem:"HSIC = 0 的等價條件（用 characteristic kernel）為？", stem_en:"HSIC = 0 iff?",
          A:"X 與 Y 線性無關", A_en:"Linearly uncorrelated", B:"X 與 Y 完全獨立", B_en:"Statistically independent",
          C:"樣本不足", C_en:"Insufficient samples", D:"均為高斯", D_en:"Both Gaussian", ans:"B",
          exp:"HSIC 是完全獨立的等價條件。", exp_en:"HSIC characterizes full independence." },
        { type:"single", stem:"下列哪情境最適合 dCor 而非 Pearson？", stem_en:"Best for dCor over Pearson?",
          A:"簡單線性回歸", A_en:"Simple linear regression", B:"計算均值", B_en:"Computing means",
          C:"50D PCA embedding 與 batch label 的依賴", C_en:"50D PCA vs batch label",
          D:"畫 UMAP", D_en:"Plotting UMAP", ans:"C", exp:"高維+非線性是 dCor 強項。", exp_en:"High-dim + non-linear is dCor's domain." },
        { type:"single", stem:"Gaussian kernel 的 σ 常用何種啟發式？", stem_en:"Common σ heuristic for Gaussian kernel?",
          A:"取 1.0", A_en:"Use 1.0", B:"median heuristic（成對距離中位數）", B_en:"Median heuristic",
          C:"取最大距離", C_en:"Max distance", D:"訓練學習", D_en:"Learned from data", ans:"B",
          exp:"median heuristic 是業界標準。", exp_en:"Median heuristic is the workhorse." },
        { type:"tf", stem:"HSIC 與 Gaussian kernel 等價於 distance correlation 平方。", stem_en:"HSIC with Gaussian kernel ≡ dCor².",
          ans:"F", exp:"是 energy kernel HSIC ≡ dCor²；Gaussian 不同。", exp_en:"Only energy-kernel HSIC ≡ dCor²; Gaussian differs." }
      ],
      ch03: [
        { type:"single", stem:"I(X;Y) = 0 等價於？", stem_en:"I(X;Y) = 0 iff?",
          A:"X ⫫ Y", A_en:"X ⫫ Y", B:"X = Y", B_en:"X = Y",
          C:"Pearson r = 1", C_en:"r = 1", D:"X 高斯", D_en:"Gaussian", ans:"A",
          exp:"MI = 0 ⇔ 完全獨立。", exp_en:"MI = 0 iff full independence." },
        { type:"single", stem:"下列哪個是神經 MI 估計？", stem_en:"Which is neural MI estimator?",
          A:"KSG", A_en:"KSG", B:"MINE", B_en:"MINE", C:"binning", C_en:"binning",
          D:"ARACNE", D_en:"ARACNE", ans:"B", exp:"MINE 用 NN 最大化 DV 下界。", exp_en:"MINE = NN-based DV bound." },
        { type:"single", stem:"PIDC 把 I(X₁,X₂;Y) 拆成？", stem_en:"PIDC decomposes I(X₁,X₂;Y) into?",
          A:"unique + redundant + synergistic", A_en:"unique + redundant + synergistic",
          B:"mean + variance", B_en:"mean + variance", C:"PC1 + PC2", C_en:"PC1 + PC2",
          D:"train + test", D_en:"train + test", ans:"A", exp:"PID = partial info decomposition。", exp_en:"PID = partial info decomposition." },
        { type:"multi", stem:"下列何者建立在 MI 之上？(多選)", stem_en:"Which are MI-based methods? (multi)",
          A:"ARACNE", A_en:"ARACNE", B:"CLR", B_en:"CLR", C:"InfoNCE", C_en:"InfoNCE",
          D:"PCA", D_en:"PCA", ans:["A","B","C"], exp:"ARACNE/CLR/InfoNCE 都是 MI-based；PCA 不是。", exp_en:"ARACNE/CLR/InfoNCE all MI-based; PCA not." }
      ],
      ch04: [
        { type:"single", stem:"Sinkhorn 演算法的關鍵 trick？", stem_en:"Sinkhorn's key trick?",
          A:"熵正則化 → O(n²/ε) 可微", A_en:"Entropic reg → O(n²/ε) differentiable",
          B:"用神經網路", B_en:"NN-based", C:"不需 cost matrix", C_en:"No cost matrix",
          D:"只能 1D", D_en:"1D only", ans:"A", exp:"熵 + scaling + GPU 友善是 Sinkhorn 三招。", exp_en:"Entropy + scaling + GPU." },
        { type:"single", stem:"Waddington-OT 解決什麼？", stem_en:"Waddington-OT solves?",
          A:"PCA", A_en:"PCA", B:"細胞無法跨時間點測量 → 用 OT 對映群體", B_en:"Cells can't be measured at multiple t → OT maps cohorts",
          C:"分群", C_en:"Clustering", D:"移除 dropout", D_en:"Removing dropout", ans:"B",
          exp:"WOT 重建跨時間細胞對應。", exp_en:"WOT reconstructs cohort correspondence." },
        { type:"single", stem:"Gromov-Wasserstein 用在何時？", stem_en:"When to use Gromov-Wasserstein?",
          A:"分布在同空間", A_en:"Same space", B:"分布在不同空間（無共同 cost）", B_en:"Different spaces (no shared cost)",
          C:"只 1D", C_en:"1D only", D:"必須有 label", D_en:"Labels required", ans:"B",
          exp:"GW 比較成對距離結構，跨空間。", exp_en:"GW compares pairwise distance structure across spaces." },
        { type:"tf", stem:"Unbalanced OT 允許兩分布質量不等。", stem_en:"Unbalanced OT allows unequal masses.",
          ans:"T", exp:"處理增殖/凋亡時需要。", exp_en:"Needed for proliferation/apoptosis." }
      ],
      ch05: [
        { type:"single", stem:"β₁ 代表？", stem_en:"β₁ represents?",
          A:"連通分支", A_en:"Components", B:"迴圈/孔洞", B_en:"Loops/holes",
          C:"空腔", C_en:"Voids", D:"交點", D_en:"Intersections", ans:"B",
          exp:"β₁ = 一維同調 = 迴圈。", exp_en:"β₁ = 1-dim homology = loops." },
        { type:"single", stem:"persistence diagram 上遠離對角線的點代表？", stem_en:"Points far from diagonal mean?",
          A:"噪音", A_en:"Noise", B:"真實顯著拓撲", B_en:"Real significant topology",
          C:"錯誤", C_en:"Errors", D:"缺值", D_en:"Missing", ans:"B",
          exp:"長壽 = 真實結構。", exp_en:"Long persistence = real structure." },
        { type:"single", stem:"Mapper 的核心步驟？", stem_en:"Mapper's core?",
          A:"lens + 局部群聚 + 圖建構", A_en:"Lens + local clustering + graph",
          B:"PCA + k-means", B_en:"PCA + k-means", C:"NN", C_en:"NN", D:"SVM", D_en:"SVM",
          ans:"A", exp:"Mapper 三步：投影、cover、群聚。", exp_en:"Mapper: project, cover, cluster." }
      ],
      ch06: [
        { type:"single", stem:"Chari & Pachter 2023 主要警告？", stem_en:"Chari & Pachter 2023 warns?",
          A:"PCA 不可靠", A_en:"PCA unreliable", B:"UMAP/t-SNE 視覺化可能誤導", B_en:"UMAP/t-SNE can mislead",
          C:"scRNA-seq 不準", C_en:"scRNA-seq inaccurate", D:"R 不適合", D_en:"R unfit", ans:"B",
          exp:"影響整個 scRNA-seq 視覺化文化。", exp_en:"Influential warning." },
        { type:"single", stem:"Diffusion maps 嵌入空間歐式距離近似？", stem_en:"Euclidean distance in diffusion maps approximates?",
          A:"Manhattan", A_en:"Manhattan", B:"Hamming", B_en:"Hamming",
          C:"Diffusion distance", C_en:"Diffusion distance", D:"Cosine", D_en:"Cosine", ans:"C",
          exp:"這是 diffusion maps 核心數學保證。", exp_en:"Core math guarantee." },
        { type:"single", stem:"PHATE 特色？", stem_en:"PHATE's feature?",
          A:"同時保留分群與軌跡連續性", A_en:"Preserves clusters AND trajectory continuity",
          B:"1D only", B_en:"1D only", C:"無高維", C_en:"No high-dim", D:"GPU required", D_en:"GPU required",
          ans:"A", exp:"potential heat-diffusion + MDS。", exp_en:"Potential heat-diffusion + MDS." }
      ],
      ch07: [
        { type:"single", stem:"RNA velocity 用什麼訊號？", stem_en:"RNA velocity uses?",
          A:"細胞數", A_en:"Cell count", B:"UMI", B_en:"UMI",
          C:"spliced/unspliced 比例", C_en:"Spliced/unspliced ratio",
          D:"拷貝數", D_en:"Copy number", ans:"C", exp:"velocity 的根基。", exp_en:"The foundation." },
        { type:"single", stem:"下列何者讓 RNA velocity 不可靠？", stem_en:"What makes velocity unreliable?",
          A:"> 1000 細胞", A_en:"> 1000 cells",
          B:"成熟組織、慢動力、低 unspliced", B_en:"Mature tissue, slow dynamics, low unspliced",
          C:"用 10x", C_en:"Using 10x", D:"UMAP", D_en:"UMAP", ans:"B",
          exp:"穩態與慢動力是 velocity 陷阱。", exp_en:"Steady-state and slow dynamics fail." },
        { type:"single", stem:"Dynamo 多了什麼？", stem_en:"Dynamo adds?",
          A:"連續向量場、Jacobian、加速度", A_en:"Continuous vector field, Jacobian, acceleration",
          B:"更少功能", B_en:"Fewer features", C:"無 Python", C_en:"No Python", D:"只 R", D_en:"R only",
          ans:"A", exp:"Dynamo 連續動力學框架。", exp_en:"Continuous dynamics framework." }
      ],
      ch08: [
        { type:"single", stem:"為何線性 pseudotime 無法描述細胞週期？", stem_en:"Why does linear pseudotime fail for cell cycle?",
          A:"太慢", A_en:"Too slow", B:"細胞週期是圓——無起點", B_en:"Cycle is a loop — no root",
          C:"太短", C_en:"Too short", D:"只 1 基因", D_en:"1 gene only", ans:"B",
          exp:"閉合迴圈不能線性化。", exp_en:"Closed loops resist linearization." },
        { type:"single", stem:"Tricycle 主要優勢？", stem_en:"Tricycle's main advantage?",
          A:"不需基因", A_en:"No genes", B:"預訓練 circular embedding，跨資料集穩定",
          B_en:"Pretrained circular embedding, stable across datasets",
          C:"只斑馬魚", C_en:"Zebrafish only", D:"GPU required", D_en:"GPU required", ans:"B",
          exp:"transfer learning 是 tricycle 關鍵。", exp_en:"Transfer learning is the key." }
      ],
      ch09: [
        { type:"single", stem:"GCN over-smoothing 是什麼？", stem_en:"GCN over-smoothing?",
          A:"訓練太快", A_en:"Trains too fast",
          B:"層數過多，所有節點特徵趨同", B_en:"Too many layers → features converge",
          C:"不能 GPU", C_en:"No GPU", D:"不能 mini-batch", D_en:"No mini-batch", ans:"B",
          exp:"鄰居平均過頭。", exp_en:"Too much neighbor averaging." },
        { type:"single", stem:"SpaGCN 與 STAGATE 共同？", stem_en:"SpaGCN and STAGATE share?",
          A:"利用空間鄰近圖整合位置+表現", A_en:"Use spatial neighbor graph + expression",
          B:"無表現", B_en:"No expression", C:"只 R", C_en:"R only", D:"非 GNN", D_en:"Not GNN", ans:"A",
          exp:"兩者都是 spatial GNN 代表。", exp_en:"Both are spatial GNN." },
        { type:"single", stem:"圖 Laplacian 的小特徵值對應？", stem_en:"Small eigenvalues correspond to?",
          A:"高頻", A_en:"High freq", B:"低頻、平滑、連通", B_en:"Low freq, smooth, connectivity",
          C:"噪音", C_en:"Noise", D:"缺值", D_en:"Missing", ans:"B",
          exp:"低 λ = 低頻。", exp_en:"Low λ = low freq." }
      ],
      ch10: [
        { type:"single", stem:"Moran's I > 0 顯著表示？", stem_en:"Positive Moran's I means?",
          A:"鄰近 spot 值相似（空間聚集）", A_en:"Neighbors similar (clustering)",
          B:"完全隨機", B_en:"Random", C:"樣本太少", C_en:"Few samples", D:"錯誤", D_en:"Errors",
          ans:"A", exp:"I > 0 = 空間聚集。", exp_en:"I > 0 = clustering." },
        { type:"single", stem:"SPARK-X 比 SpatialDE 主要勝在？", stem_en:"SPARK-X over SpatialDE?",
          A:"完全相同", A_en:"Identical", B:"記憶體多", B_en:"More memory",
          C:"速度 100×，可達 10⁵ spots", C_en:"100× faster, 10⁵ spots",
          D:"R only", D_en:"R only", ans:"C", exp:"核-線性技巧加速。", exp_en:"Kernel-linear trick." },
        { type:"single", stem:"nnSVG 主要特色？", stem_en:"nnSVG's main feature?",
          A:"每基因 fit NN-GP，給基因專屬長度尺度", A_en:"Per-gene NN-GP; gene-specific length scale",
          B:"只 PCA", B_en:"Just PCA", C:"無 SVG", C_en:"No SVG", D:"GPU only", D_en:"GPU only",
          ans:"A", exp:"對異質尺度好。", exp_en:"Handles heterogeneous scales." }
      ],
      ch11: [
        { type:"single", stem:"ELBO 兩項是？", stem_en:"Two terms of ELBO?",
          A:"lr + batch size", A_en:"lr + batch size", B:"細胞數 + 基因數", B_en:"Cells + genes",
          C:"重構誤差 + 先驗 KL", C_en:"Reconstruction + prior KL",
          D:"train + test", D_en:"train + test", ans:"C",
          exp:"重構 + KL = ELBO。", exp_en:"Reconstruction + KL." },
        { type:"single", stem:"reparameterization trick 解決？", stem_en:"What does reparam trick solve?",
          A:"讓 q(z|x) 抽樣可微", A_en:"Makes q(z|x) differentiable",
          B:"擴大模型", B_en:"Bigger model", C:"資料載入", C_en:"Data loading", D:"壓縮模型", D_en:"Compress",
          ans:"A", exp:"VAE 訓練關鍵。", exp_en:"Key to VAE training." },
        { type:"single", stem:"scVI 用什麼分布建模 counts？", stem_en:"scVI count distribution?",
          A:"NB / ZINB", A_en:"NB / ZINB", B:"Gaussian", B_en:"Gaussian",
          C:"Bernoulli", C_en:"Bernoulli", D:"Uniform", D_en:"Uniform", ans:"A",
          exp:"計數適合 NB/ZINB。", exp_en:"Counts suit NB/ZINB." }
      ],
      ch12: [
        { type:"single", stem:"擴散網路在學什麼？", stem_en:"What does diffusion net learn?",
          A:"分類", A_en:"Classification", B:"細胞數", B_en:"Counts",
          C:"每步加入的噪音（≡ ∇ log p(x)）", C_en:"Per-step noise (≡ score)",
          D:"基因標籤", D_en:"Gene labels", ans:"C", exp:"學 score function。", exp_en:"Learns score." },
        { type:"single", stem:"代表性生物應用？", stem_en:"Representative bio app?",
          A:"Pearson", A_en:"Pearson", B:"RFdiffusion 設計新蛋白", B_en:"RFdiffusion designs proteins",
          C:"分群", C_en:"Clustering", D:"PCA", D_en:"PCA", ans:"B",
          exp:"RFdiffusion 是 2023 里程碑。", exp_en:"RFdiffusion 2023 landmark." }
      ],
      ch13: [
        { type:"single", stem:"scGPT 與 Geneformer 的核心差異？", stem_en:"Core diff between scGPT and Geneformer?",
          A:"用 SVM", A_en:"Uses SVM",
          B:"scGPT token = (gene, expr)；Geneformer token = gene symbol 並依排名", B_en:"scGPT (gene, expr) tokens; Geneformer rank-ordered gene tokens",
          C:"相同", C_en:"Identical", D:"非 transformer", D_en:"Not transformer", ans:"B",
          exp:"tokenization 策略是兩者差異。", exp_en:"Tokenization differs." },
        { type:"single", stem:"2025-2026 benchmark 結論？", stem_en:"2025-2026 benchmark conclusion?",
          A:"完全取代", A_en:"Fully replace traditional", B:"一無是處", B_en:"Useless",
          C:"沒有單一模型勝出；某些任務未明顯勝 baseline", C_en:"No single winner; some tasks no clear win over baselines",
          D:"只 scGPT 有用", D_en:"Only scGPT useful", ans:"C",
          exp:"審慎評估。", exp_en:"Evaluate carefully." }
      ],
      ch14: [
        { type:"single", stem:"p(B|A) 與 p(B|do(A)) 差異？", stem_en:"p(B|A) vs p(B|do(A))?",
          A:"相同", A_en:"Identical", B:"do(A) 較慢", B_en:"do(A) slower",
          C:"p(B|A) 觀察條件機率；p(B|do(A)) 干預機率", C_en:"Observational vs interventional",
          D:"do(A) 是 Pearson", D_en:"do(A) is Pearson", ans:"C",
          exp:"do(·) 切斷上游。", exp_en:"do(·) severs upstream." },
        { type:"single", stem:"Perturb-seq 在因果推論價值？", stem_en:"Perturb-seq's causal value?",
          A:"提升 PCR", A_en:"Improves PCR",
          B:"主動干預 → 真正 do(·) 觀測", B_en:"Active perturbation → real do(·) data",
          C:"增加細胞數", C_en:"More cells", D:"移除 dropout", D_en:"Removes dropout", ans:"B",
          exp:"因果黃金資料。", exp_en:"Gold-standard data." }
      ],
      ch15: [
        { type:"single", stem:"雙曲空間為何適合樹狀？", stem_en:"Why hyperbolic for trees?",
          A:"計算快", A_en:"Faster",
          B:"負曲率讓圓的體積指數成長", B_en:"Negative curvature → exponential volume",
          C:"GPU", C_en:"GPU", D:"線性", D_en:"Linear", ans:"B",
          exp:"雙曲幾何核心優勢。", exp_en:"Core hyperbolic advantage." },
        { type:"single", stem:"Poincaré disk 點限制在？", stem_en:"Poincaré disk points?",
          A:"R²", A_en:"R²", B:"單位圓內部 ‖x‖<1", B_en:"Inside unit disk",
          C:"單位圓上", C_en:"On circle", D:"第一象限", D_en:"First quadrant", ans:"B",
          exp:"開放單位圓盤。", exp_en:"Open unit disk." },
        { type:"single", stem:"Poincaré maps 最適用？", stem_en:"Best Poincaré maps use?",
          A:"分群", A_en:"Clustering",
          B:"細胞型別 ontology / 分化階層", B_en:"Cell-type ontology / lineage hierarchy",
          C:"PCA", C_en:"PCA", D:"Pearson", D_en:"Pearson", ans:"B",
          exp:"階層是雙曲強項。", exp_en:"Hierarchies are hyperbolic's forte." }
      ],
      ch16: [
        { type:"single", stem:"Neural ODE 把神經網路視為？", stem_en:"Neural ODE views NN as?",
          A:"離散層", A_en:"Discrete layers",
          B:"連續時間動力 dh/dt = f(h,t,θ)", B_en:"Continuous dynamics dh/dt = f(h,t,θ)",
          C:"GAN", C_en:"GAN", D:"隨機矩陣", D_en:"Random matrices", ans:"B",
          exp:"ResNet 連續極限。", exp_en:"ResNet's continuous limit." },
        { type:"single", stem:"Chen 2018 用什麼訓練？", stem_en:"What does Chen 2018 use?",
          A:"Adjoint method（O(1) 記憶體）", A_en:"Adjoint method (O(1) memory)",
          B:"全 backprop", B_en:"Full backprop", C:"Monte Carlo", C_en:"Monte Carlo",
          D:"Markov chain", D_en:"Markov chain", ans:"A",
          exp:"adjoint 是 NeurIPS best paper 核心貢獻。", exp_en:"Adjoint is the key contribution." }
      ],
      ch17: [
        { type:"single", stem:"Flow Matching vs Diffusion 主要優勢？", stem_en:"FM over Diffusion?",
          A:"更慢", A_en:"Slower",
          B:"訓練更穩定、step 少、目標簡單", B_en:"More stable, fewer steps, simpler",
          C:"GPU 多", C_en:"More GPU", D:"只 1D", D_en:"1D only", ans:"B",
          exp:"Lipman 2023 重點。", exp_en:"Main point of Lipman 2023." },
        { type:"single", stem:"AlphaFlow 用 FM 做？", stem_en:"AlphaFlow uses FM for?",
          A:"分群", A_en:"Clustering",
          B:"蛋白結構 ensemble 生成", B_en:"Protein structure ensembles",
          C:"Pearson", C_en:"Pearson", D:"序列壓縮", D_en:"Sequence compression", ans:"B",
          exp:"AlphaFold 改 ensemble 版。", exp_en:"AlphaFold → ensemble." }
      ],
      ch18: [
        { type:"single", stem:"Mamba 比 Transformer 在長序列優勢？", stem_en:"Mamba vs Transformer for long seqs?",
          A:"相同", A_en:"Same", B:"O(n) vs O(n²)", B_en:"O(n) vs O(n²)",
          C:"更小參數", C_en:"Fewer params", D:"有 attention map", D_en:"Has attention map", ans:"B",
          exp:"Selective scan 給線性。", exp_en:"Selective scan = linear." },
        { type:"single", stem:"HyenaDNA/Caduceus 用在？", stem_en:"HyenaDNA/Caduceus for?",
          A:"分群", A_en:"Clustering", B:"1M bp 全基因組長序列建模", B_en:"1M-bp genome modeling",
          C:"PCA", C_en:"PCA", D:"圖像", D_en:"Images", ans:"B",
          exp:"長 context 是 SSM 強項。", exp_en:"Long context is SSM's." }
      ],
      ch19: [
        { type:"single", stem:"Conformal prediction 主要保證？", stem_en:"Conformal's main guarantee?",
          A:"點預測準度", A_en:"Point accuracy",
          B:"P(Y ∈ C(X)) ≥ 1−α，分布無關", B_en:"P(Y ∈ C(X)) ≥ 1−α, distribution-free",
          C:"最快訓練", C_en:"Fastest training", D:"最少記憶體", D_en:"Least memory", ans:"B",
          exp:"distribution-free coverage。", exp_en:"Distribution-free coverage." },
        { type:"single", stem:"Split conformal 需要？", stem_en:"Split conformal needs?",
          A:"只訓練集", A_en:"Train only",
          B:"訓練集 + calibration set", B_en:"Train + calibration set",
          C:"只 test", C_en:"Test only", D:"無資料", D_en:"No data", ans:"B",
          exp:"校正集計算 quantile。", exp_en:"Cal set for quantile." }
      ],
      ch20: [
        { type:"single", stem:"Bayesian Optimization 兩元件？", stem_en:"BO's two components?",
          A:"CNN + Transformer", A_en:"CNN + Transformer",
          B:"Surrogate (GP) + Acquisition", B_en:"Surrogate (GP) + Acquisition",
          C:"PCA + UMAP", C_en:"PCA + UMAP", D:"GAN + VAE", D_en:"GAN + VAE", ans:"B",
          exp:"GP + acquisition。", exp_en:"GP + acquisition." },
        { type:"single", stem:"典型生資 BO 應用？", stem_en:"Typical BO bio app?",
          A:"下一個 CRISPR 該打哪個基因", A_en:"Next CRISPR: which gene?",
          B:"Pearson", B_en:"Pearson", C:"UMAP", C_en:"UMAP", D:"序列壓縮", D_en:"Compression",
          ans:"A", exp:"BO 指引昂貴實驗。", exp_en:"BO guides expensive experiments." }
      ],
      ch21: [
        { type:"single", stem:"IB 優化目標？", stem_en:"IB objective?",
          A:"min I(X;T) − β·I(T;Y)", A_en:"min I(X;T) − β·I(T;Y)",
          B:"min L2", B_en:"min L2", C:"max r", C_en:"max r", D:"min KL only", D_en:"min KL only",
          ans:"A", exp:"壓縮 X 但保留 Y。", exp_en:"Compress X, keep Y info." },
        { type:"single", stem:"VIB 關鍵貢獻？", stem_en:"VIB's key contribution?",
          A:"變分化 IB 可微分", A_en:"Variational IB, differentiable",
          B:"更快", B_en:"Faster", C:"更小", C_en:"Smaller", D:"GAN", D_en:"GAN", ans:"A",
          exp:"Alemi 2017 把 IB 變 DL。", exp_en:"Alemi 2017 made IB into DL." }
      ],
      ch22: [
        { type:"single", stem:"CP decomposition 寫成？", stem_en:"CP writes a tensor as?",
          A:"rank-1 張量和 T ≈ Σ a⊗b⊗c", A_en:"Sum of rank-1 tensors",
          B:"矩陣乘積", B_en:"Matrix product", C:"PCA 元件", C_en:"PCA components",
          D:"NN", D_en:"NN", ans:"A", exp:"Canonical Polyadic 分解。", exp_en:"Canonical Polyadic." },
        { type:"single", stem:"Tensor-cell2cell 處理？", stem_en:"Tensor-cell2cell handles?",
          A:"分群", A_en:"Clustering",
          B:"多病人 × 細胞型別 × 基因 cell-cell 通訊張量", B_en:"Patient × cell-type × gene CCC tensor",
          C:"PCA", C_en:"PCA", D:"序列壓縮", D_en:"Compression", ans:"B",
          exp:"天生適合 3D+ omics。", exp_en:"Natural for 3D+ omics." }
      ],
      ch23: [
        { type:"single", stem:"InfoNCE 數學等價於？", stem_en:"InfoNCE equivalent to?",
          A:"MI 下界", A_en:"MI lower bound", B:"Cross-entropy", B_en:"Cross-entropy",
          C:"L2 loss", C_en:"L2 loss", D:"GAN loss", D_en:"GAN loss", ans:"A",
          exp:"van den Oord 2018。", exp_en:"van den Oord 2018." },
        { type:"single", stem:"SimCLR 怎麼產生 positive pair？", stem_en:"How does SimCLR make positives?",
          A:"兩 augmentation 同一張圖", A_en:"Two augmentations of same image",
          B:"隨機兩張", B_en:"Two random images", C:"GAN 生成", C_en:"GAN-generated",
          D:"人工標註", D_en:"Manual labels", ans:"A",
          exp:"augmentation 是核心。", exp_en:"Augmentation is core." },
        { type:"single", stem:"CLIP 核心特色？", stem_en:"CLIP's core feature?",
          A:"單模態", A_en:"Single-modal",
          B:"跨模態對比學習（影像↔文字）", B_en:"Cross-modal contrastive (image↔text)",
          C:"GAN", C_en:"GAN", D:"PCA", D_en:"PCA", ans:"B",
          exp:"大規模 image-caption。", exp_en:"Image-caption pairs at scale." }
      ],
      ch24: [
        { type:"single", stem:"SINDy 找的是什麼？", stem_en:"SINDy finds?",
          A:"分群", A_en:"Clusters",
          B:"動態資料的 ODE 形式 dx/dt = f(x)", B_en:"ODE form dx/dt = f(x) from data",
          C:"PCA", C_en:"PCA", D:"GRN", D_en:"GRN", ans:"B",
          exp:"稀疏回歸於候選函式庫。", exp_en:"Sparse regression on library." },
        { type:"single", stem:"符號回歸相比 NN 的優勢？", stem_en:"SR's advantage over NN?",
          A:"更可解釋（closed-form）", A_en:"More interpretable (closed-form)",
          B:"訓練快", B_en:"Faster training", C:"省記憶體", C_en:"Less memory", D:"GPU", D_en:"GPU",
          ans:"A", exp:"expression 可讀。", exp_en:"Readable expressions." }
      ],
      ch25: [
        { type:"single", stem:"Sheaf Laplacian 推廣自？", stem_en:"Sheaf Laplacian generalizes?",
          A:"graph Laplacian", A_en:"Graph Laplacian", B:"PCA", B_en:"PCA",
          C:"NN", C_en:"NN", D:"GAN", D_en:"GAN", ans:"A",
          exp:"Hansen & Ghrist 2019。", exp_en:"Hansen & Ghrist 2019." },
        { type:"single", stem:"Cellular sheaf 適合？", stem_en:"Cellular sheaves fit?",
          A:"單基因", A_en:"Single gene",
          B:"節點間有 disagreement / 多模態不一致", B_en:"Nodes with disagreement / multi-modal inconsistency",
          C:"純樹狀", C_en:"Pure trees", D:"隨機", D_en:"Random", ans:"B",
          exp:"sheaf 天生處理不一致。", exp_en:"Sheaves handle inconsistency." }
      ],
      ch26: [
        { type:"single", stem:"SE(3)-equivariance 意指？", stem_en:"SE(3)-equivariance means?",
          A:"對 3D 旋轉+平移等價/不變", A_en:"Equivariant under 3D rotation+translation",
          B:"縮放不變", B_en:"Scale-invariant", C:"亮度不變", C_en:"Brightness-invariant",
          D:"PCA 不變", D_en:"PCA-invariant", ans:"A",
          exp:"SE(3) = 3D 剛體變換群。", exp_en:"SE(3) = 3D rigid body group." },
        { type:"single", stem:"AlphaFold2 evoformer 含？", stem_en:"AlphaFold2 evoformer contains?",
          A:"SE(3)-equivariant attention", A_en:"SE(3)-equivariant attention",
          B:"GAN", B_en:"GAN", C:"隨機森林", C_en:"Random forest", D:"PCA", D_en:"PCA",
          ans:"A", exp:"AF2 關鍵設計。", exp_en:"Key AF2 design." }
      ],
      ch27: [
        { type:"single", stem:"Modern Hopfield Networks 數學等價於？", stem_en:"Modern Hopfield ≡?",
          A:"GAN", A_en:"GAN", B:"softmax attention", B_en:"softmax attention",
          C:"PCA", C_en:"PCA", D:"k-NN", D_en:"k-NN", ans:"B",
          exp:"Ramsauer 2021 證明。", exp_en:"Ramsauer 2021 proved this." },
        { type:"single", stem:"HopfieldRepertoire 應用？", stem_en:"HopfieldRepertoire used for?",
          A:"PCA", A_en:"PCA",
          B:"TCR/BCR 免疫倉庫變單檢索", B_en:"TCR/BCR immune repertoire retrieval",
          C:"分群", C_en:"Clustering", D:"GAN", D_en:"GAN", ans:"B",
          exp:"免疫倉庫變單檢索。", exp_en:"Immune repertoire retrieval." }
      ],
      ch28: [
        { type:"single", stem:"Direct Coupling Analysis 預測什麼？", stem_en:"DCA predicts?",
          A:"細胞型別", A_en:"Cell types", B:"蛋白接觸（contact map）", B_en:"Protein contacts (contact map)",
          C:"基因表現", C_en:"Gene expression", D:"PCA", D_en:"PCA", ans:"B",
          exp:"從 MSA 推接觸，AlphaFold 前身。", exp_en:"From MSA → contacts; AF predecessor." },
        { type:"single", stem:"EBM 機率形式？", stem_en:"EBM probability form?",
          A:"p(x) = exp(−E(x))/Z", A_en:"p(x) = exp(−E(x))/Z",
          B:"p(x) = E(x)", B_en:"p(x) = E(x)", C:"p(x) = max", C_en:"p(x) = max",
          D:"p(x) = sum", D_en:"p(x) = sum", ans:"A",
          exp:"Boltzmann 分布。", exp_en:"Boltzmann distribution." }
      ],
      ch29: [
        { type:"single", stem:"Hawkes 過程的關鍵特徵？", stem_en:"Hawkes process key feature?",
          A:"事件獨立", A_en:"Independent events",
          B:"自激發——過往事件提升未來機率", B_en:"Self-exciting — past events raise future rate",
          C:"週期", C_en:"Periodic", D:"常數速率", D_en:"Constant rate", ans:"B",
          exp:"自激發是 Hawkes 核心。", exp_en:"Self-excitation is core." },
        { type:"single", stem:"Hawkes 在生資典型應用？", stem_en:"Hawkes typical bio app?",
          A:"PCA", A_en:"PCA",
          B:"體細胞突變時序、神經 spike train", B_en:"Somatic mutation timing, neural spike trains",
          C:"分群", C_en:"Clustering", D:"GAN", D_en:"GAN", ans:"B",
          exp:"非獨立事件時序。", exp_en:"Non-independent event timing." }
      ],
      ch30: [
        { type:"single", stem:"REINVENT 用於？", stem_en:"REINVENT used for?",
          A:"分群", A_en:"Clustering",
          B:"RNN + RL 生成藥物分子", B_en:"RNN + RL drug molecule generation",
          C:"PCA", C_en:"PCA", D:"GAN", D_en:"GAN", ans:"B",
          exp:"Olivecrona 2017 藥物設計。", exp_en:"Drug design (Olivecrona 2017)." },
        { type:"single", stem:"PPO 屬於？", stem_en:"PPO is?",
          A:"Value-based", A_en:"Value-based",
          B:"Policy gradient（actor-critic 變體）", B_en:"Policy gradient (actor-critic variant)",
          C:"Tree search", C_en:"Tree search", D:"Random", D_en:"Random", ans:"B",
          exp:"Schulman 2017。", exp_en:"Schulman 2017." }
      ],
      ch31: [
        { type:"single", stem:"Marchenko-Pastur 定律告訴我們？", stem_en:"Marchenko-Pastur tells us?",
          A:"GAN 訓練法", A_en:"GAN training",
          B:"隨機 covariance 矩陣 eigenvalue 分布",
          B_en:"Eigenvalue distribution of random covariance matrices",
          C:"PCA 速度", C_en:"PCA speed", D:"Pearson r 範圍", D_en:"Pearson r range", ans:"B",
          exp:"用於 GRN 降噪。", exp_en:"Used for GRN denoising." },
        { type:"single", stem:"Eigengene (Alter 2003) 啟發了什麼？", stem_en:"Eigengene (Alter 2003) inspired?",
          A:"GAN", A_en:"GAN",
          B:"用 SVD/RMT 找 gene expression 的真信號 vs 噪音", B_en:"SVD/RMT to find true gene signal vs noise",
          C:"GPU", C_en:"GPU", D:"k-means", D_en:"k-means", ans:"B",
          exp:"RMT 在 omics 的開創應用。", exp_en:"Pioneering RMT in omics." }
      ],
      ch32: [
        { type:"single", stem:"Sliced-Wasserstein 的關鍵 trick？", stem_en:"Sliced-W's trick?",
          A:"用 GAN", A_en:"GAN-based",
          B:"投影到 1D 平均多個 W₁", B_en:"Project to 1D and average many W₁",
          C:"PCA", C_en:"PCA", D:"k-means", D_en:"k-means", ans:"B",
          exp:"1D Wasserstein 有封閉形式。", exp_en:"1D Wasserstein has closed form." },
        { type:"single", stem:"SW 相比 Sinkhorn？", stem_en:"SW vs Sinkhorn?",
          A:"慢", A_en:"Slower", B:"快約 100× 適合 atlas-scale", B_en:"~100× faster, atlas-scale",
          C:"完全相同", C_en:"Identical", D:"非可微", D_en:"Non-differentiable", ans:"B",
          exp:"速度是 SW 賣點。", exp_en:"Speed is SW's appeal." }
      ],
      ch33: [
        { type:"single", stem:"壓縮感測核心想法？", stem_en:"Compressed sensing core idea?",
          A:"M < N 量測重建稀疏信號", A_en:"Recover sparse signal from M < N measurements",
          B:"GAN", B_en:"GAN", C:"PCA", C_en:"PCA", D:"k-NN", D_en:"k-NN", ans:"A",
          exp:"L1 凸最佳化。", exp_en:"L1 convex optimization." },
        { type:"single", stem:"MERFISH 應用 CS 原理做什麼？", stem_en:"How does MERFISH use CS?",
          A:"分群", A_en:"Clustering",
          B:"以 ~100 探針偵測 1000+ 基因", B_en:"Detect 1000+ genes with ~100 probes",
          C:"PCA", C_en:"PCA", D:"GAN", D_en:"GAN", ans:"B",
          exp:"barcode = 稀疏編碼。", exp_en:"Barcoding = sparse coding." }
      ],
      ch34: [
        { type:"single", stem:"小波比傅立葉強在？", stem_en:"Wavelets over Fourier?",
          A:"更快", A_en:"Faster",
          B:"時間-頻率局部化（兩者兼顧）", B_en:"Time-frequency localization (both axes)",
          C:"GPU", C_en:"GPU", D:"PCA", D_en:"PCA", ans:"B",
          exp:"Fourier 只有頻率。", exp_en:"Fourier only does frequency." },
        { type:"single", stem:"DWT 計算複雜度？", stem_en:"DWT complexity?",
          A:"O(n)", A_en:"O(n)", B:"O(n log n)", B_en:"O(n log n)",
          C:"O(n²)", C_en:"O(n²)", D:"O(n³)", D_en:"O(n³)", ans:"A",
          exp:"pyramid algorithm O(n)。", exp_en:"Pyramid algorithm O(n)." }
      ],
      ch35: [
        { type:"single", stem:"INR 用什麼表示信號？", stem_en:"How do INRs represent signals?",
          A:"離散像素", A_en:"Discrete pixels",
          B:"連續函式 f_θ(座標) → 值", B_en:"Continuous function f_θ(coords) → value",
          C:"GAN", C_en:"GAN", D:"PCA", D_en:"PCA", ans:"B",
          exp:"NN 編碼整個信號。", exp_en:"NN encodes the signal." },
        { type:"single", stem:"SIREN 用什麼 activation 提升高頻表示？", stem_en:"What activation does SIREN use?",
          A:"ReLU", A_en:"ReLU", B:"sine", B_en:"sine",
          C:"tanh", C_en:"tanh", D:"sigmoid", D_en:"sigmoid", ans:"B",
          exp:"Sitzmann 2020 的關鍵。", exp_en:"Sitzmann 2020's key." }
      ],
      ch36: [
        { type:"single", stem:"DPP 給什麼樣本高機率？", stem_en:"DPP gives high probability to?",
          A:"最相似樣本", A_en:"Most similar samples",
          B:"多元且彼此不重複的子集", B_en:"Diverse, non-redundant subsets",
          C:"隨機", C_en:"Random", D:"順序", D_en:"Ordered", ans:"B",
          exp:"det(L_Y) 偏好 diversity。", exp_en:"det(L_Y) prefers diversity." },
        { type:"single", stem:"DPP 在生資典型應用？", stem_en:"DPP typical bio app?",
          A:"PCA", A_en:"PCA",
          B:"marker gene 選取、panel 設計", B_en:"Marker gene selection, panel design",
          C:"分群", C_en:"Clustering", D:"GAN", D_en:"GAN", ans:"B",
          exp:"挑多元代表的工具。", exp_en:"Tool for picking diverse representatives." }
      ],
      ch37: [
        { type:"single", stem:"FedAvg 主要做什麼？", stem_en:"FedAvg does?",
          A:"集中所有資料訓練", A_en:"Centralize all data",
          B:"各 client 本地訓練 → 上傳權重 → 平均", B_en:"Local train → upload weights → average",
          C:"GAN", C_en:"GAN", D:"PCA", D_en:"PCA", ans:"B",
          exp:"McMahan 2017。", exp_en:"McMahan 2017." },
        { type:"single", stem:"FL 在生醫的主要動機？", stem_en:"FL's main motivation in biomedicine?",
          A:"速度", A_en:"Speed",
          B:"隱私保護——不分享原始資料", B_en:"Privacy — no raw data sharing",
          C:"GPU 省", C_en:"GPU savings", D:"記憶體", D_en:"Memory", ans:"B",
          exp:"多醫院合作不違反 HIPAA。", exp_en:"Multi-hospital collab without HIPAA breach." }
      ],
      ch38: [
        { type:"single", stem:"Hypergraph 與 graph 主要差異？", stem_en:"Hypergraph vs graph?",
          A:"無差", A_en:"None",
          B:"一條邊可連接 ≥3 個節點", B_en:"One edge connects ≥3 nodes",
          C:"少節點", C_en:"Fewer nodes", D:"必有向", D_en:"Always directed", ans:"B",
          exp:"hyperedge 是「複數節點關係」的自然語言。", exp_en:"Hyperedges naturally express multi-node relations." },
        { type:"single", stem:"超圖適合哪類生資資料？", stem_en:"Hypergraph fits what bio data?",
          A:"單基因", A_en:"Single gene",
          B:"multi-omics、L-R complex、epistasis", B_en:"multi-omics, L-R complex, epistasis",
          C:"PCA", C_en:"PCA", D:"GAN", D_en:"GAN", ans:"B",
          exp:"多元高階互動。", exp_en:"Higher-order multi-node interactions." }
      ]
    }
  }
};
